export enum EMensagem {
  AutenticadoSucesso = 'Autenticado com sucesso',
  AtualizadoSucesso = 'Atualizado com sucesso',
  DesativadoSucesso = 'Desativado com sucesso',
  DeveSerVazio = 'deve ser vazio',
  DeveSerInformado = 'deve ser informado',
  ErroExportarPDF = 'Erro ao exportar PDF',
  ExcluidoSucesso = 'Excluído com sucesso',
  FilterInvalido = 'Filter inválido',
  ImpossivelCadastrar = 'Impossível realizar esse cadastro',
  ImpossivelAlterar = 'Impossível alterar',
  IniciadaGeracaoPDF = 'Iniciada a geração do PDF',
  IDsDiferentes = 'Os IDs informados são diferentes',
  MaisCaracteresPermitido = 'contém mais caracteres do que o permitido',
  NaoPodeSerVazio = 'não pode ser vazio',
  NaoValido = 'não é válido',
  OrderInvalido = 'Order inválido',
  SalvoSucesso = 'Salvo com sucesso',
  TokenInvalido = 'Token inválido',
  ProdutoSenhaInvalido = 'Usuário e/ou senha inválidos',
  VerifiqueEnderecoEmailInformado = 'Verifique o endereço de e-mail informado',
}
